# -*- coding: utf-8 -*-
"""k-medias

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/108jRtI1_3RGFJKv8Lf7uhYhyMjNCuxcW
"""

import cv2
import matplotlib.pyplot as plt 
import numpy as np

#leer imagen 
original_img = cv2.imread('raven.jpg')

#se convierte la imagen a un formato 
img = cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB)
plt.imshow(img)
plt.show()

vectorized = img.reshape((-1,3))
vectorized = np.float32(vectorized)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
k = 5
attempts = 10
ret, label, center = cv2.kmeans(vectorized,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
center= np.uint8(center)
res=center[label.flatten()]
result_img = res.reshape((img.shape))

plt.figure(figsize=(15,15))
plt.subplot(1,2,1), plt.imshow(img)
plt.title('Imagen Original'), plt.xticks([]), plt.yticks([])
plt.subplot(1,2,2), plt.imshow(result_img)
plt.title('Imagen Segmentada con K = %i' %k),plt.xticks([]), plt.yticks([])
plt.show()

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt 

plt.rcParams['figure.figsize'] = (12,6)
plt.style.use('ggplot')

data = pd.read_csv('http://dicyg.fi-c.unam.mx:8080/lalo/pypcd/presentaciones/xclara.csv')
data.shape

data.head()

plt.scatter(data.V1.values, data.V2.values, s=7)

from sklearn.cluster import KMeans

f1 = data.V1.values
f2 = data.V2.values
x = np.array(list(zip(f1,f2)))

kmeans = KMeans(n_clusters = 3)

#ajuste

kmeans = kmeans.fit(x)

#etiquetas

y = kmeans.predict(x)

#centroides

c_ = kmeans.cluster_centers_

y

fig, ax = plt.subplots()
ax.scatter(x[:,0], x[:,1], c=y)
ax.scatter(c_[:,0], c_[:,1], marker='*', s=200, c='k')